apiVersion: v1
kind: Pod
metadata:
  labels:
    run: megazord-multi-container
  name: megazord-multi-container
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - name: primeiro-emptydir
      mountPath: /primeiro-emptydir-path
    args:
    - sleep
    - infinity
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
  - image: nginx
    name: nginx
    volumeMounts:
    - name: primeiro-emptydir
      mountPath: /primeiro-emptydir-path
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 500Mi
