apiVersion: v1
kind: Pod
metadata:
  labels:
    run: megazord
  name: megazord
spec:
  containers:
  - image: ubuntu
    name: megazord
    volumeMounts:
    - name: primeiro-emptydir
      mountPath: /primeiro-emptydir-path
    args:
    - sleep
    - infinity
    resources:
      limits:
        cpu: "1"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 500Mi
