apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
  name: girus
spec:
  containers:
  - image: nginx
    name: girus
    ports:
    - containerPort: 80
    resources: {}
  - image: busybox
    name: busybox
    args:
    - sleep
    - '600'
  dnsPolicy: ClusterFirst
  restartPolicy: Always

