apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  type: NodePort  # Expõe o serviço em uma porta acessível externamente
  selector:
    app: node-exporter
  ports:
    - protocol: TCP
      port: 9100         # Porta interna do Service
      targetPort: 9100   # Porta do pod do node-exporter
      nodePort: 30100    # Porta exposta no nó (deve estar entre 30000-32767)

