apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-giropops
  name: nginx-giropops
  namespace: giropops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-giropops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-giropops
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources: {}
status: {}
