apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"nginx-giropops"},"name":"nginx-giropops","namespace":"giropops"},"spec":{"replicas":10,"selector":{"matchLabels":{"app":"nginx-giropops"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx-giropops"}},"spec":{"containers":[{"image":"nginx:1.15.0","name":"nginx","resources":{}}]}}},"status":{}}
  creationTimestamp: "2025-03-14T13:21:12Z"
  generation: 1
  labels:
    app: nginx-giropops
  name: nginx-giropops
  namespace: giropops
  resourceVersion: "151325"
  uid: 63b7139d-af29-4286-b927-98a06b24e002
spec:
  progressDeadlineSeconds: 600
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-giropops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-giropops
    spec:
      containers:
      - image: nginx:1.15.0
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2025-03-14T13:21:26Z"
    lastUpdateTime: "2025-03-14T13:21:26Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-03-14T13:21:12Z"
    lastUpdateTime: "2025-03-14T13:21:28Z"
    message: ReplicaSet "nginx-giropops-6cb65599f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
