apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: strigus
  name: strigus
spec:
  containers:
  - image: nginx
    name: strigus
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
